---
title: "Worksheet-2 in R"
output:
  html_document: default
  pdf_document: default
date: "2023-10-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r num1a}
seqA <- -5:5
seqA

```

```{r num1b}
x <- 1:7
x

```

```{r num2}
vecseq <- seq(1, 3, by=0.2)
vecseq

```

```{r num3a}
Cencus <- c(34,28,22,36,27,18,52,39,42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,18)

Cen3rd <- Cencus[3]
Cen3rd
```

```{r num3b}
Cencus[c(2, 4)]
Cencus

```

```{r num3c}
Not1 <- Cencus[-4]
Not1
Not2 <- Cencus [-13]
Not2

NotBoth <- c(Not1, Not2)
NotBoth
```

```{r num4}
x <- c("first"=3, "second"=0, "third"=9)
names(x)
x [c ("first", "third")]
```

```{r num5}
x <- -3:2
x[2] <- 0
x

```

```{r num6a}
month <- c("Jan", "Feb", "March", "Apr", "May", "June")
price_per_liter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase_quantity <- c(25, 30, 40, 50, 10, 45)

df <- data.frame(Month = month, Price_Per_Liter = price_per_liter, Purchase_Quantity = purchase_quantity)
df
```

```{r num6b}
avgfuelexp <- weighted.mean(price_per_liter, purchase_quantity)
avgfuelexp
```

```{r num7}
rivers
rivers <- rivers [1:7]
rivers
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),
          sd(rivers), min(rivers), max(rivers))
data
```

```{r num8a}
CelebData <- data.frame (
  PowerRanking = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25),
  CelebrityName = c("Tom Cruise" , "Rolling Stones", "Oprah Winfrey", "U2","Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Lenon", "Celine Dion", "Kobe Bryant"),
  Pay = c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)
)
CelebData
```

```{r num8b}
RepNew <- replace(CelebData$PowerRanking, 19, 15)
PayNew <- replace(CelebData$Pay, 19, 90)

NewCelebData <- data.frame (
  PowerRanking = RepNew, CelebData$CelebrityName, Pay = PayNew)
NewCelebData

```

```{r num8c}
install.packages("writexl")
library(writexl)
write_xlsx(CelebData, path = "PowerRanking.xlsx")
write.csv(CelebData, file = "PowerRanking.csv", row.names = FALSE)
```

```{r num8d}
TntoTwnty <-CelebData[10:20, ]
save(TntoTwnty, file = "Ranks.RData")
TntoTwnty
```

```{r num9a}
library(readxl)
ExcData <- read_excel("hotels-vienna.xlsx")
ExcData
```

```{r num9b}
dimensions <- dim(ExcData)
dimensions
```


```{r num9c}
selected_columns <- ExcData[, c("country", "neighbourhood", "price", "stars", "accommodation_type", "rating")]
head(selected_columns, n = nrow(selected_columns))
```

```{r num9d}
save(selected_columns, file = "new.RData")
```

```{r num9e}
load("new.RData")
head(selected_columns)
tail(selected_columns)

```

```{r num10a}
Veggies <- c("Tomato","Carrot","Potatoes","Cucumber","Eggplant","Bell Pepper","Squash","Cabbage","Radish","Mushroom")
Veggies 

```

```{r num10b}
AddVeg<- c("Kangkong","Ampalaya")
LastVeg<-c(Veggies, AddVeg)
LastVeg
```

```{r num10c}
FourVeg<- c("Artichoke", "Beet", "Broccolli", "Sitaw")
UpdateVeg <- c(LastVeg[1:5], FourVeg, LastVeg[6:length(LastVeg)])
UpdateVeg

length(UpdateVeg)
```

```{r num10d}
Bye<- c(5, 10, 15)
Final<-UpdateVeg[-Bye]
Final

length(Final)
```