---
title: "RMarkdown_Somosera#4b"
output:
  pdf_document: default
  html_document: default
date: "2023-11-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r num1}
vecA <- c(1,2,3,4,5) 
matA <- matrix(0, nrow = 5, ncol = 5) 

for (i in 1:5){ 
  for (j in 1:5){ 
    matA[i,j] <- abs(vecA[i]-vecA[j]) #
  }
}

print(matA) 

```


```{r num2}
asterisks <- "" 
for(i in 1:5){  
asterisks <- paste(asterisks, "*") 

cat(asterisks, "\n")
}

```

```{r num3}

n <- as.integer(readline(prompt="Enter the number of terms: "))

a <- 0
b <- 1

print(b)

repeat {
  c <- a + b
  if (c > 500) {
    break
  }
  print(c)
  a <- b
  b <- c
}
```


```{r num4}
#a
library(readr)
HouseholdData <- read_csv("/cloud/project/Worksheet#4/Worksheet#4b/HouseholdData.csv")
print(HouseholdData)

head(HouseholdData)

#b
MaleSub<- subset(HouseholdData, Gender == "Male")
FemSub<- subset(HouseholdData, Gender =="Female")

print("Male Subset:")
print(MaleSub)

print("Female Subset:")
print(FemSub)

nrow(MaleSub)
nrow(FemSub)

#c
GraphMF<- table(HouseholdData$Gender)
barplot(GraphMF,
        main = "Number of Males and Females",
        xlab = "Gender",
        ylab = "Count",
        col = c("dodgerblue4", "hotpink4"), 
        legend.text = c("Male", "Female"),
        beside = TRUE
)

legend("topright", legend = c("Male", "Female"), fill = c("dodgerblue4", "hotpink4"))
```

```{r num5}
Expenses <- c(Food = 60, Electricity = 10, Savings = 5, Miscellaneous = 25)

pie(Expenses,
    labels = paste(names(Expenses), "\n", sprintf("%.1f%%", prop.table(Expenses) * 100)),
    col = c("slateblue", "violetred4", "violetred", "magenta4"),  
    main = "Monthly Expenses of the Dela Cruz Family"
)
```

```{r num6}
#a
data("iris")
str(iris)

#The iris dataset has 150 observations and 5 variables.
#These variables are the Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, and Species.

#b
MeanIris<- colMeans(iris[, c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width")])
print(MeanIris)

#c
Spec <- table(iris$Species)

clors <- c("midnightblue", "mediumvioletred", "mediumblue")

pie(Spec,
    labels = paste(names(Spec), "\n", sprintf("%.1f%%", prop.table(Spec) * 100)),
    col = clors,
    main = "Species Distribution",
    cex.main = 1.5, 
    cex = 0.8      
)

#d
SetosaSub <- subset(iris, Species == "setosa")
VersiSub <- subset(iris, Species == "versicolor")
VirgiSub <- subset(iris, Species == "virginica")

# Display the last six rows of each species
cat("Last six rows of Setosa:")
print(tail(SetosaSub))

cat("Last six rows of Versicolor:")
print(tail(VersiSub))

cat("Last six rows of Virginica:")
print(tail(VirgiSub))


#e

data(iris)

iris$Species <- as.factor(iris$Species)

plot(iris$Sepal.Length, iris$Sepal.Width,
     pch = as.integer(iris$Species), 
     col = iris$Species, 
     main = "Iris Dataset",
     sub = "Sepal width and length",
     xlab = "Sepal Length",
     ylab = "Sepal Width"
)

#f
#The scatterplot shows similarities between the sepal width and length ranging from 5.5 to 7.0
```

```{r num7}
library(readxl)
alexa_file <- read_excel("/cloud/project/Worksheet#4/Worksheet#4b/alexa_file.xlsx")
alexa_file

#a. Rename the white and black variants by using gsub() function.
alexa_file$variation <- gsub("Black", "Black Dot", alexa_file$variation)
alexa_file$variation <- gsub("Black", "Black Plus", alexa_file$variation)
alexa_file$variation <- gsub("Black", "Black Snow", alexa_file$variation)
alexa_file$variation <- gsub("Black", "Black Spot", alexa_file$variation)
alexa_file$variation <- gsub("White", "White Dot", alexa_file$variation)
alexa_file$variation <- gsub("White", "White Plus", alexa_file$variation)
alexa_file$variation <- gsub("White", "White Snow", alexa_file$variation)
alexa_file$variation <- gsub("White", "White Spot", alexa_file$variation)
alexa_file

library(knitr)
```

